name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '1.25.0'
      - run: docker-compose run app "python manage.py test && flake8"

